VAGRANT_FILE_API_VERSION = "2"

Vagrant.configure(VAGRANT_FILE_API_VERSION) do |config|
	# Define the box to work with it
	config.vm.box = "jaxmetalmax/debian-jessie-8.5-x32"

	#configure the update script
	$script = %Q{
		sudo apt-get update
		sudo apt-get install nasm make build-essential grub qemu zip -y --force-yes
	}

	#configure virtual machine mode
	config.vm.provision :shell, :inline => $script
end
